import type { Country } from "./countries";

/** Every country/territory with its calling code (generated from libphonenumber), sorted by French name. */
export const WORLD_COUNTRIES: Country[] = [
  { id: "AF", dial: "+93", fr: "Afghanistan", en: "Afghanistan" },
  { id: "ZA", dial: "+27", fr: "Afrique du Sud", en: "South Africa" },
  { id: "AL", dial: "+355", fr: "Albanie", en: "Albania" },
  { id: "DZ", dial: "+213", fr: "Algérie", en: "Algeria" },
  { id: "DE", dial: "+49", fr: "Allemagne", en: "Germany" },
  { id: "AD", dial: "+376", fr: "Andorre", en: "Andorra" },
  { id: "AO", dial: "+244", fr: "Angola", en: "Angola" },
  { id: "AI", dial: "+1", fr: "Anguilla", en: "Anguilla" },
  { id: "AG", dial: "+1", fr: "Antigua-et-Barbuda", en: "Antigua & Barbuda" },
  { id: "SA", dial: "+966", fr: "Arabie saoudite", en: "Saudi Arabia" },
  { id: "AR", dial: "+54", fr: "Argentine", en: "Argentina" },
  { id: "AM", dial: "+374", fr: "Arménie", en: "Armenia" },
  { id: "AW", dial: "+297", fr: "Aruba", en: "Aruba" },
  { id: "AU", dial: "+61", fr: "Australie", en: "Australia" },
  { id: "AT", dial: "+43", fr: "Autriche", en: "Austria" },
  { id: "AZ", dial: "+994", fr: "Azerbaïdjan", en: "Azerbaijan" },
  { id: "BS", dial: "+1", fr: "Bahamas", en: "Bahamas" },
  { id: "BH", dial: "+973", fr: "Bahreïn", en: "Bahrain" },
  { id: "BD", dial: "+880", fr: "Bangladesh", en: "Bangladesh" },
  { id: "BB", dial: "+1", fr: "Barbade", en: "Barbados" },
  { id: "BE", dial: "+32", fr: "Belgique", en: "Belgium" },
  { id: "BZ", dial: "+501", fr: "Belize", en: "Belize" },
  { id: "BJ", dial: "+229", fr: "Bénin", en: "Benin" },
  { id: "BM", dial: "+1", fr: "Bermudes", en: "Bermuda" },
  { id: "BT", dial: "+975", fr: "Bhoutan", en: "Bhutan" },
  { id: "BY", dial: "+375", fr: "Biélorussie", en: "Belarus" },
  { id: "BO", dial: "+591", fr: "Bolivie", en: "Bolivia" },
  { id: "BA", dial: "+387", fr: "Bosnie-Herzégovine", en: "Bosnia & Herzegovina" },
  { id: "BW", dial: "+267", fr: "Botswana", en: "Botswana" },
  { id: "BR", dial: "+55", fr: "Brésil", en: "Brazil" },
  { id: "BN", dial: "+673", fr: "Brunei", en: "Brunei" },
  { id: "BG", dial: "+359", fr: "Bulgarie", en: "Bulgaria" },
  { id: "BF", dial: "+226", fr: "Burkina Faso", en: "Burkina Faso" },
  { id: "BI", dial: "+257", fr: "Burundi", en: "Burundi" },
  { id: "KH", dial: "+855", fr: "Cambodge", en: "Cambodia" },
  { id: "CM", dial: "+237", fr: "Cameroun", en: "Cameroon" },
  { id: "CA", dial: "+1", fr: "Canada", en: "Canada" },
  { id: "CV", dial: "+238", fr: "Cap-Vert", en: "Cape Verde" },
  { id: "CL", dial: "+56", fr: "Chili", en: "Chile" },
  { id: "CN", dial: "+86", fr: "Chine", en: "China" },
  { id: "CY", dial: "+357", fr: "Chypre", en: "Cyprus" },
  { id: "CO", dial: "+57", fr: "Colombie", en: "Colombia" },
  { id: "KM", dial: "+269", fr: "Comores", en: "Comoros" },
  { id: "CG", dial: "+242", fr: "Congo-Brazzaville", en: "Congo - Brazzaville" },
  { id: "CD", dial: "+243", fr: "Congo-Kinshasa", en: "Congo - Kinshasa" },
  { id: "KP", dial: "+850", fr: "Corée du Nord", en: "North Korea" },
  { id: "KR", dial: "+82", fr: "Corée du Sud", en: "South Korea" },
  { id: "CR", dial: "+506", fr: "Costa Rica", en: "Costa Rica" },
  { id: "CI", dial: "+225", fr: "Côte d’Ivoire", en: "Côte d’Ivoire" },
  { id: "HR", dial: "+385", fr: "Croatie", en: "Croatia" },
  { id: "CU", dial: "+53", fr: "Cuba", en: "Cuba" },
  { id: "CW", dial: "+599", fr: "Curaçao", en: "Curaçao" },
  { id: "DK", dial: "+45", fr: "Danemark", en: "Denmark" },
  { id: "DJ", dial: "+253", fr: "Djibouti", en: "Djibouti" },
  { id: "DM", dial: "+1", fr: "Dominique", en: "Dominica" },
  { id: "EG", dial: "+20", fr: "Égypte", en: "Egypt" },
  { id: "AE", dial: "+971", fr: "Émirats arabes unis", en: "United Arab Emirates" },
  { id: "EC", dial: "+593", fr: "Équateur", en: "Ecuador" },
  { id: "ER", dial: "+291", fr: "Érythrée", en: "Eritrea" },
  { id: "ES", dial: "+34", fr: "Espagne", en: "Spain" },
  { id: "EE", dial: "+372", fr: "Estonie", en: "Estonia" },
  { id: "SZ", dial: "+268", fr: "Eswatini", en: "Eswatini" },
  { id: "VA", dial: "+39", fr: "État de la Cité du Vatican", en: "Vatican City" },
  { id: "US", dial: "+1", fr: "États-Unis", en: "United States" },
  { id: "ET", dial: "+251", fr: "Éthiopie", en: "Ethiopia" },
  { id: "FJ", dial: "+679", fr: "Fidji", en: "Fiji" },
  { id: "FI", dial: "+358", fr: "Finlande", en: "Finland" },
  { id: "FR", dial: "+33", fr: "France", en: "France" },
  { id: "GA", dial: "+241", fr: "Gabon", en: "Gabon" },
  { id: "GM", dial: "+220", fr: "Gambie", en: "Gambia" },
  { id: "GE", dial: "+995", fr: "Géorgie", en: "Georgia" },
  { id: "GH", dial: "+233", fr: "Ghana", en: "Ghana" },
  { id: "GI", dial: "+350", fr: "Gibraltar", en: "Gibraltar" },
  { id: "GR", dial: "+30", fr: "Grèce", en: "Greece" },
  { id: "GD", dial: "+1", fr: "Grenade", en: "Grenada" },
  { id: "GL", dial: "+299", fr: "Groenland", en: "Greenland" },
  { id: "GP", dial: "+590", fr: "Guadeloupe", en: "Guadeloupe" },
  { id: "GU", dial: "+1", fr: "Guam", en: "Guam" },
  { id: "GT", dial: "+502", fr: "Guatemala", en: "Guatemala" },
  { id: "GG", dial: "+44", fr: "Guernesey", en: "Guernsey" },
  { id: "GN", dial: "+224", fr: "Guinée", en: "Guinea" },
  { id: "GQ", dial: "+240", fr: "Guinée équatoriale", en: "Equatorial Guinea" },
  { id: "GW", dial: "+245", fr: "Guinée-Bissau", en: "Guinea-Bissau" },
  { id: "GY", dial: "+592", fr: "Guyana", en: "Guyana" },
  { id: "GF", dial: "+594", fr: "Guyane française", en: "French Guiana" },
  { id: "HT", dial: "+509", fr: "Haïti", en: "Haiti" },
  { id: "HN", dial: "+504", fr: "Honduras", en: "Honduras" },
  { id: "HU", dial: "+36", fr: "Hongrie", en: "Hungary" },
  { id: "CX", dial: "+61", fr: "Île Christmas", en: "Christmas Island" },
  { id: "IM", dial: "+44", fr: "Île de Man", en: "Isle of Man" },
  { id: "NF", dial: "+672", fr: "Île Norfolk", en: "Norfolk Island" },
  { id: "AX", dial: "+358", fr: "Îles Åland", en: "Åland Islands" },
  { id: "KY", dial: "+1", fr: "Îles Caïmans", en: "Cayman Islands" },
  { id: "CC", dial: "+61", fr: "Îles Cocos", en: "Cocos (Keeling) Islands" },
  { id: "CK", dial: "+682", fr: "Îles Cook", en: "Cook Islands" },
  { id: "FO", dial: "+298", fr: "Îles Féroé", en: "Faroe Islands" },
  { id: "FK", dial: "+500", fr: "Îles Malouines", en: "Falkland Islands" },
  { id: "MP", dial: "+1", fr: "Îles Mariannes du Nord", en: "Northern Mariana Islands" },
  { id: "MH", dial: "+692", fr: "Îles Marshall", en: "Marshall Islands" },
  { id: "SB", dial: "+677", fr: "Îles Salomon", en: "Solomon Islands" },
  { id: "TC", dial: "+1", fr: "Îles Turques-et-Caïques", en: "Turks & Caicos Islands" },
  { id: "VG", dial: "+1", fr: "Îles Vierges britanniques", en: "British Virgin Islands" },
  { id: "VI", dial: "+1", fr: "Îles Vierges des États-Unis", en: "U.S. Virgin Islands" },
  { id: "IN", dial: "+91", fr: "Inde", en: "India" },
  { id: "ID", dial: "+62", fr: "Indonésie", en: "Indonesia" },
  { id: "IQ", dial: "+964", fr: "Irak", en: "Iraq" },
  { id: "IR", dial: "+98", fr: "Iran", en: "Iran" },
  { id: "IE", dial: "+353", fr: "Irlande", en: "Ireland" },
  { id: "IS", dial: "+354", fr: "Islande", en: "Iceland" },
  { id: "IL", dial: "+972", fr: "Israël", en: "Israel" },
  { id: "IT", dial: "+39", fr: "Italie", en: "Italy" },
  { id: "JM", dial: "+1", fr: "Jamaïque", en: "Jamaica" },
  { id: "JP", dial: "+81", fr: "Japon", en: "Japan" },
  { id: "JE", dial: "+44", fr: "Jersey", en: "Jersey" },
  { id: "JO", dial: "+962", fr: "Jordanie", en: "Jordan" },
  { id: "KZ", dial: "+7", fr: "Kazakhstan", en: "Kazakhstan" },
  { id: "KE", dial: "+254", fr: "Kenya", en: "Kenya" },
  { id: "KG", dial: "+996", fr: "Kirghizstan", en: "Kyrgyzstan" },
  { id: "KI", dial: "+686", fr: "Kiribati", en: "Kiribati" },
  { id: "XK", dial: "+383", fr: "Kosovo", en: "Kosovo" },
  { id: "KW", dial: "+965", fr: "Koweït", en: "Kuwait" },
  { id: "RE", dial: "+262", fr: "La Réunion", en: "Réunion" },
  { id: "LA", dial: "+856", fr: "Laos", en: "Laos" },
  { id: "LS", dial: "+266", fr: "Lesotho", en: "Lesotho" },
  { id: "LV", dial: "+371", fr: "Lettonie", en: "Latvia" },
  { id: "LB", dial: "+961", fr: "Liban", en: "Lebanon" },
  { id: "LR", dial: "+231", fr: "Liberia", en: "Liberia" },
  { id: "LY", dial: "+218", fr: "Libye", en: "Libya" },
  { id: "LI", dial: "+423", fr: "Liechtenstein", en: "Liechtenstein" },
  { id: "LT", dial: "+370", fr: "Lituanie", en: "Lithuania" },
  { id: "LU", dial: "+352", fr: "Luxembourg", en: "Luxembourg" },
  { id: "MK", dial: "+389", fr: "Macédoine du Nord", en: "North Macedonia" },
  { id: "MG", dial: "+261", fr: "Madagascar", en: "Madagascar" },
  { id: "MY", dial: "+60", fr: "Malaisie", en: "Malaysia" },
  { id: "MW", dial: "+265", fr: "Malawi", en: "Malawi" },
  { id: "MV", dial: "+960", fr: "Maldives", en: "Maldives" },
  { id: "ML", dial: "+223", fr: "Mali", en: "Mali" },
  { id: "MT", dial: "+356", fr: "Malte", en: "Malta" },
  { id: "MA", dial: "+212", fr: "Maroc", en: "Morocco" },
  { id: "MQ", dial: "+596", fr: "Martinique", en: "Martinique" },
  { id: "MU", dial: "+230", fr: "Maurice", en: "Mauritius" },
  { id: "MR", dial: "+222", fr: "Mauritanie", en: "Mauritania" },
  { id: "YT", dial: "+262", fr: "Mayotte", en: "Mayotte" },
  { id: "MX", dial: "+52", fr: "Mexique", en: "Mexico" },
  { id: "FM", dial: "+691", fr: "Micronésie", en: "Micronesia" },
  { id: "MD", dial: "+373", fr: "Moldavie", en: "Moldova" },
  { id: "MC", dial: "+377", fr: "Monaco", en: "Monaco" },
  { id: "MN", dial: "+976", fr: "Mongolie", en: "Mongolia" },
  { id: "ME", dial: "+382", fr: "Monténégro", en: "Montenegro" },
  { id: "MS", dial: "+1", fr: "Montserrat", en: "Montserrat" },
  { id: "MZ", dial: "+258", fr: "Mozambique", en: "Mozambique" },
  { id: "MM", dial: "+95", fr: "Myanmar (Birmanie)", en: "Myanmar (Burma)" },
  { id: "NA", dial: "+264", fr: "Namibie", en: "Namibia" },
  { id: "NR", dial: "+674", fr: "Nauru", en: "Nauru" },
  { id: "NP", dial: "+977", fr: "Népal", en: "Nepal" },
  { id: "NI", dial: "+505", fr: "Nicaragua", en: "Nicaragua" },
  { id: "NE", dial: "+227", fr: "Niger", en: "Niger" },
  { id: "NG", dial: "+234", fr: "Nigeria", en: "Nigeria" },
  { id: "NU", dial: "+683", fr: "Niue", en: "Niue" },
  { id: "NO", dial: "+47", fr: "Norvège", en: "Norway" },
  { id: "NC", dial: "+687", fr: "Nouvelle-Calédonie", en: "New Caledonia" },
  { id: "NZ", dial: "+64", fr: "Nouvelle-Zélande", en: "New Zealand" },
  { id: "OM", dial: "+968", fr: "Oman", en: "Oman" },
  { id: "UG", dial: "+256", fr: "Ouganda", en: "Uganda" },
  { id: "UZ", dial: "+998", fr: "Ouzbékistan", en: "Uzbekistan" },
  { id: "PK", dial: "+92", fr: "Pakistan", en: "Pakistan" },
  { id: "PW", dial: "+680", fr: "Palaos", en: "Palau" },
  { id: "PA", dial: "+507", fr: "Panama", en: "Panama" },
  { id: "PG", dial: "+675", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea" },
  { id: "PY", dial: "+595", fr: "Paraguay", en: "Paraguay" },
  { id: "NL", dial: "+31", fr: "Pays-Bas", en: "Netherlands" },
  { id: "BQ", dial: "+599", fr: "Pays-Bas caribéens", en: "Caribbean Netherlands" },
  { id: "PE", dial: "+51", fr: "Pérou", en: "Peru" },
  { id: "PH", dial: "+63", fr: "Philippines", en: "Philippines" },
  { id: "PL", dial: "+48", fr: "Pologne", en: "Poland" },
  { id: "PF", dial: "+689", fr: "Polynésie française", en: "French Polynesia" },
  { id: "PR", dial: "+1", fr: "Porto Rico", en: "Puerto Rico" },
  { id: "PT", dial: "+351", fr: "Portugal", en: "Portugal" },
  { id: "QA", dial: "+974", fr: "Qatar", en: "Qatar" },
  { id: "HK", dial: "+852", fr: "R.A.S. chinoise de Hong Kong", en: "Hong Kong SAR China" },
  { id: "MO", dial: "+853", fr: "R.A.S. chinoise de Macao", en: "Macao SAR China" },
  { id: "CF", dial: "+236", fr: "République centrafricaine", en: "Central African Republic" },
  { id: "DO", dial: "+1", fr: "République dominicaine", en: "Dominican Republic" },
  { id: "RO", dial: "+40", fr: "Roumanie", en: "Romania" },
  { id: "GB", dial: "+44", fr: "Royaume-Uni", en: "United Kingdom" },
  { id: "RU", dial: "+7", fr: "Russie", en: "Russia" },
  { id: "RW", dial: "+250", fr: "Rwanda", en: "Rwanda" },
  { id: "EH", dial: "+212", fr: "Sahara occidental", en: "Western Sahara" },
  { id: "BL", dial: "+590", fr: "Saint-Barthélemy", en: "St. Barthélemy" },
  { id: "KN", dial: "+1", fr: "Saint-Christophe-et-Niévès", en: "St. Kitts & Nevis" },
  { id: "SM", dial: "+378", fr: "Saint-Marin", en: "San Marino" },
  { id: "MF", dial: "+590", fr: "Saint-Martin", en: "St. Martin" },
  { id: "SX", dial: "+1", fr: "Saint-Martin (partie néerlandaise)", en: "Sint Maarten" },
  { id: "PM", dial: "+508", fr: "Saint-Pierre-et-Miquelon", en: "St. Pierre & Miquelon" },
  { id: "VC", dial: "+1", fr: "Saint-Vincent-et-les Grenadines", en: "St. Vincent & Grenadines" },
  { id: "SH", dial: "+290", fr: "Sainte-Hélène", en: "St. Helena" },
  { id: "LC", dial: "+1", fr: "Sainte-Lucie", en: "St. Lucia" },
  { id: "SV", dial: "+503", fr: "Salvador", en: "El Salvador" },
  { id: "WS", dial: "+685", fr: "Samoa", en: "Samoa" },
  { id: "AS", dial: "+1", fr: "Samoa américaines", en: "American Samoa" },
  { id: "ST", dial: "+239", fr: "Sao Tomé-et-Principe", en: "São Tomé & Príncipe" },
  { id: "SN", dial: "+221", fr: "Sénégal", en: "Senegal" },
  { id: "RS", dial: "+381", fr: "Serbie", en: "Serbia" },
  { id: "SC", dial: "+248", fr: "Seychelles", en: "Seychelles" },
  { id: "SL", dial: "+232", fr: "Sierra Leone", en: "Sierra Leone" },
  { id: "SG", dial: "+65", fr: "Singapour", en: "Singapore" },
  { id: "SK", dial: "+421", fr: "Slovaquie", en: "Slovakia" },
  { id: "SI", dial: "+386", fr: "Slovénie", en: "Slovenia" },
  { id: "SO", dial: "+252", fr: "Somalie", en: "Somalia" },
  { id: "SD", dial: "+249", fr: "Soudan", en: "Sudan" },
  { id: "SS", dial: "+211", fr: "Soudan du Sud", en: "South Sudan" },
  { id: "LK", dial: "+94", fr: "Sri Lanka", en: "Sri Lanka" },
  { id: "SE", dial: "+46", fr: "Suède", en: "Sweden" },
  { id: "CH", dial: "+41", fr: "Suisse", en: "Switzerland" },
  { id: "SR", dial: "+597", fr: "Suriname", en: "Suriname" },
  { id: "SJ", dial: "+47", fr: "Svalbard et Jan Mayen", en: "Svalbard & Jan Mayen" },
  { id: "SY", dial: "+963", fr: "Syrie", en: "Syria" },
  { id: "TJ", dial: "+992", fr: "Tadjikistan", en: "Tajikistan" },
  { id: "TW", dial: "+886", fr: "Taïwan", en: "Taiwan" },
  { id: "TZ", dial: "+255", fr: "Tanzanie", en: "Tanzania" },
  { id: "TD", dial: "+235", fr: "Tchad", en: "Chad" },
  { id: "CZ", dial: "+420", fr: "Tchéquie", en: "Czechia" },
  { id: "IO", dial: "+246", fr: "Territoire britannique de l’océan Indien", en: "British Indian Ocean Territory" },
  { id: "PS", dial: "+970", fr: "Territoires palestiniens", en: "Palestinian Territories" },
  { id: "TH", dial: "+66", fr: "Thaïlande", en: "Thailand" },
  { id: "TL", dial: "+670", fr: "Timor oriental", en: "Timor-Leste" },
  { id: "TG", dial: "+228", fr: "Togo", en: "Togo" },
  { id: "TK", dial: "+690", fr: "Tokelau", en: "Tokelau" },
  { id: "TO", dial: "+676", fr: "Tonga", en: "Tonga" },
  { id: "TT", dial: "+1", fr: "Trinité-et-Tobago", en: "Trinidad & Tobago" },
  { id: "TN", dial: "+216", fr: "Tunisie", en: "Tunisia" },
  { id: "TM", dial: "+993", fr: "Turkménistan", en: "Turkmenistan" },
  { id: "TR", dial: "+90", fr: "Turquie", en: "Türkiye" },
  { id: "TV", dial: "+688", fr: "Tuvalu", en: "Tuvalu" },
  { id: "UA", dial: "+380", fr: "Ukraine", en: "Ukraine" },
  { id: "UY", dial: "+598", fr: "Uruguay", en: "Uruguay" },
  { id: "VU", dial: "+678", fr: "Vanuatu", en: "Vanuatu" },
  { id: "VE", dial: "+58", fr: "Venezuela", en: "Venezuela" },
  { id: "VN", dial: "+84", fr: "Viêt Nam", en: "Vietnam" },
  { id: "WF", dial: "+681", fr: "Wallis-et-Futuna", en: "Wallis & Futuna" },
  { id: "YE", dial: "+967", fr: "Yémen", en: "Yemen" },
  { id: "ZM", dial: "+260", fr: "Zambie", en: "Zambia" },
  { id: "ZW", dial: "+263", fr: "Zimbabwe", en: "Zimbabwe" },
];

const norm = (s: string) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[’']/g, "'").toLowerCase().trim();

/** Finds a country from its ISO id or its French/English name (as stored on cards). */
export function findWorldCountry(value?: string | null): Country | undefined {
  if (!value) return undefined;
  const v = norm(value);
  return WORLD_COUNTRIES.find((c) => c.id.toLowerCase() === v || norm(c.fr) === v || norm(c.en) === v);
}
