/**
 * Search words for every sticker (besides its name): what the image shows and the feeling it says.
 * Written from the images themselves. Plain words separated by spaces; accents are optional (search ignores them).
 */
const WIPPIE_CAPTIONS: Record<string, string> = {
  "wippe-moi": "ecris moi appelle moi contacte message clin d oeil",
  "ca-wipp": "wipp super top cool genial pouce ok",
  merci: "thanks reconnaissance coeur gentil",
  "on-se-capte": "a plus tard rendez vous bye salut lunettes",
  mdr: "rire rigoler lol haha ptdr drole larmes joie",
  hmm: "reflechir doute penser hesiter question",
  "no-way": "impossible choque surpris non pas possible omg",
  valide: "ok d accord oui parfait top bien",
  "j-arrive": "en route bientot coucou salut arriver",
  "bonne-nuit": "dodo dormir sommeil zzz lune soir",
  "bon-matin": "bonjour reveil cafe matin coucou",
  "appelle-moi": "telephone appel coup de fil tel",
  bisous: "coeur amour kiss bisou love",
  bravo: "felicitations bien joue top fete super",
  "laisse-tomber": "oublie pas grave tant pis abandonne",
  connecte: "ensemble mains accord deal ami",
  respect: "check poing frere ami",
};

export const STICKER_KEYWORDS: Record<string, string> = {
  // Wippmoji
  "moji-01": "rire rigoler mdr ptdr lol haha hihi drole marrant larmes joie",
  "moji-02": "rire rigoler mdr ptdr lol haha drole marrant larmes joie pleurer",
  "moji-03": "amour coeur love yeux je t aime crush adore",
  "moji-04": "baiser kiss coeur amour clin d oeil smack",
  "moji-05": "lunettes soleil classe style pouce top ok super",
  "moji-06": "coeur amour wipp love calin serrer tendresse",
  "moji-07": "triste pleurer larmes chagrin peine sad snif deprime",
  "moji-08": "surpris surprise quoi wow omg incroyable stupefait",
  "moji-09": "colere enerve fache rage vapeur rouge grr",
  "moji-10": "priere s il te plait stp svp pitie mains jointes reconnaissant",
  "moji-11": "triste inquiet supplier pitie desole oups",
  "moji-12": "roi couronne king boss calme serein fier",
  "moji-13": "feu chaud hot flamme brule top excellent",
  "moji-14": "etoiles emerveille wow brille paillettes ebloui",
  "moji-15": "langue taquin clin d oeil rire drole hihi coquin",
  "moji-16": "silence secret bouche cousue motus tais toi",
  "moji-17": "suspect louche doute hmm soupcon regard",
  "moji-18": "quoi question reflechir doute pardon comprends pas",
  "moji-19": "coeur amour mains love tendresse",
  "moji-20": "dormir dodo sommeil zzz fatigue nuit",
  "moji-21": "anniversaire party confettis celebrer joyeux trompette",
  "moji-22": "pouce bas nul pas terrible blase non mouais",
  "moji-23": "boisson lunettes cool chill detente soif",
  "moji-24": "ok top bien d accord valide super bravo like",
  "moji-25": "argent billets dollars money fric thune cash",
  "moji-26": "explosion tete choque wow incroyable",
  "moji-27": "coeur amour love tendresse lumiere",
  "moji-28": "courir vite rapide course j arrive presse",
  "moji-29": "rire mdr larmes joie haha drole roi reine",
  "moji-30": "coeurs amour bisou clin d oeil love kiss",
  "moji-31": "amour yeux coeur adore craquer love",
  "moji-32": "moi lunettes cool fier montrer classe",
  "moji-33": "langue fete delire fou cool metal",
  "moji-34": "reflechir penser question doute hmm idee",
  "moji-35": "gene rougir mignon coeur shy",
  "moji-36": "calin coeur amour serrer tendresse hug",
  "moji-37": "chut secret silence doigt tais toi",
  "moji-38": "fete joie confettis celebrer anniversaire hourra",
  "moji-39": "chou adorable coeurs amour craquer",
  "moji-40": "peur stress angoisse nerveux oups",
  "moji-41": "dormir dodo sommeil zzz nuage repos fatigue",
  "moji-42": "colere enerve fache furieux grr vapeur",
  "moji-43": "argent billets riche dollars money fric cash",
  "moji-44": "couronne reine joie heureuse coucou",
  "moji-45": "musique ecouter son chanson joie",
  "moji-46": "etoiles ange aureole wow brille",
  "moji-47": "ordinateur travail bureau taff boulot ecran",
  "moji-48": "fleurs roses amour cadeau coeur pour toi",
  "moji-49": "detente concombre soin beaute relax masque",
  "moji-50": "aureole innocent coeurs gentil sage",
  "moji-51": "boisson matin pause tasse chaud reveil",
  "moji-52": "sacs achats magasin courses joie",

  // Wippie Elle / Lui (same captions)
  ...Object.fromEntries(Object.entries(WIPPIE_CAPTIONS).flatMap(([id, words]) => [[id, words], [`lui-${id}`, words]])),

  // Wippie Comique
  "fun-va-la-bas": "pars degage montrer colere",
  "fun-stop": "arrete non halte main",
  "fun-hahaha": "rire mdr chien lol drole",
  "fun-pas-aujourdhui": "non flemme chat tasse",
  "fun-le-boss": "chef roi couronne trone",
  "fun-trop-tot": "fatigue reveil matin baille dormir",
  "fun-ca-marche": "ok d accord argent billets valide",
  "fun-valide": "ok panda d accord oui",
  "fun-bisousss": "kiss coeur amour bisou",
  "fun-nimporte-quoi": "colere enerve absurde",
  "fun-bien-joue": "bravo felicitations top",
  "fun-ecoute-bien": "singe casque attention",
  "fun-laisse-moi": "tranquille stop main non",
  "fun-cool": "chien lunettes classe",
  "fun-vraiment": "serieux grenouille doute quoi question",
  "fun-oh-non": "desespoir oups zut",
  "fun-yesss": "victoire joie super gagne",
  "fun-dodo": "dormir ours sommeil zzz nuit",
  "fun-tchip": "agace enerve oiseau rouge",
  "fun-focus": "concentration couronne objectif",
  "fun2-toi-la": "grand mere colere doigt montrer",
  "fun2-cours": "courir fuir tapette grand mere vite",
  "fun2-hahaha": "rire vieux mdr lol drole",
  "fun2-pas-mon-probleme": "tasse bigoudis",
  "fun2-nananana": "langue moquer taquin enfant",
  "fun2-hum": "mefiant doute casquette",
  "fun2-mdr": "rire danser lol haha drole",
  "fun2-je-suis-ko": "fatigue epuise canape dormir creve",
  "fun2-bye-bye": "au revoir salut a plus main",
  "fun2-je-vais-taper": "colere tapette menace grand mere",
  "fun2-tu-parles-trop": "bavard blabla tais toi",
  "fun2-oh-mon-dieu": "choque omg panique",
  "fun2-je-te-vois": "espionner cache mur regarde",
  "fun2-argent-dabord": "money billets fric cash",
  "fun2-degage": "va t en stop non colere",
  "fun2-cest-bon-hein": "manger nourriture miam",
  "fun2-trop-mange": "ventre plein rassasie miam",
  "fun2-wesh": "salut chevre quoi",
  "fun2-ecoutez-moi-bien": "megaphone annonce attention",
  "fun2-je-ne-sais-pas": "aucune idee epaules",
  "sig-jarrive": "en route coucou bientot",
  "sig-coucou": "salut bonjour panda hello",
  "sig-tes-la": "present coucou question",
  "sig-bonne-idee": "ampoule genial",
  "sig-cafe": "pause boisson matin tasse",
  "sig-bisous": "chien coeur amour kiss",
  "sig-mdrrr": "rire lol haha drole",
  "sig-tu-mens": "menteur chat noir mefiant",
  "sig-waaah": "wow surpris choque incroyable bebe",
  "sig-valide": "ok couronne oui parfait",
  "sig-on-se-capte": "a plus tard pouce bye",
  "sig-self-care": "soin detente spa concombre beaute",
  "sig-je-regarde": "yeux observer surveiller",
  "sig-en-route": "courir j arrive telephone",
  "sig-bonne-nuit": "dodo dormir chien sommeil",
  "sig-debout": "reveil matin alarme leve toi",
  "sig-on-regarde": "film popcorn cinema serie",
  "sig-laisse-tomber": "coeur brise triste oublie",
  "sig-hmm": "reflechir doute penser",
  "sig-shopping": "sacs achats magasin",
  "sig-voyage": "avion vacances partir",
  "sig-ma-vibe": "musique avocat casque ambiance",
  "sig-motive": "sport musculation halteres energie",
  "sig-appelle": "telephone appel",
  "sig-faim": "pizza manger miam",
  "sig-ca-paye": "argent billets salaire money",
  "sig-chill": "detente cactus lunettes coeur relax",
  "sig-toujours": "coeur fidele present",
  "sig-ca-wipp": "boule disco fete soiree",
  "sig-raconte": "potin dis moi bulle histoire",
  "scene-01": "ok top super valide",
  "scene-02": "chef top bravo couronne",
  "scene-03": "chat lunettes ambiance chill cool",
  "scene-04": "coeur gentil reconnaissance",
  "scene-05": "batterie reviens vite pause fatigue",
  "scene-06": "rire hyene mdr drole oups",
  "scene-07": "lunettes epaules",
  "scene-08": "bonjour soleil pingouin cafe matin",
  "scene-09": "kiss coeur amour",
  "scene-10": "bonne nuit dodo dormir zzz",
  "scene-11": "casque chien son chanson",
  "scene-12": "roses fleurs bouquet cadeau amour",
  "scene-13": "chaud fantome transpirer stress panique",
  "scene-14": "amour coeur yeux love",
  "scene-15": "non refus main stop",
  "scene-16": "applaudir felicitations mains clap",
  "scene-17": "apprendre cerveau livre lecture ecole",
  "scene-18": "go c est parti cafe",
  "scene-19": "sablier bientot attendre",
  "scene-20": "argent ailes billets",
  "scene-21": "a bientot terre avion voyage",
  "scene-22": "cible but viser",
  "scene-23": "robot aide",
  "scene-24": "jeu manette gaming jouer",
  "scene-25": "secret cadenas prive",
  "scene-26": "film clap cinema incroyable",
  "scene-27": "coeur doigts tendresse",
  "scene-28": "manger cheffe repas miam",
  "scene-29": "gyrophare urgence attention sirene",
  "scene-30": "coeur pansement courage reconfort",

  // EMO
  "emo-01": "victoire gagne medaille confettis bravo fete",
  "emo-02": "sacs achats magasin courses",
  "emo-03": "cache mur espionner regarde surpris",
  "emo-04": "popcorn film cinema regarder drama potin",
  "emo-05": "glisser tomber chute oups maladroit",
  "emo-06": "nettoyer balai fatigue corvee",
  "emo-07": "attends patience sablier temps retard heure",
  "emo-08": "partir voyage je m en vais bye depart",
  "emo-09": "detective enqueter chercher curieuse",
  "emo-10": "cache couverture timide peur",

  // WIPP Moments
  "ani-stop": "arrete non halte main",
  "ani-bisou": "kiss amour coeur",
  "moment-01": "coucou bonjour hello telephone",
  "moment-02": "rire lol haha drole telephone",
  "moment-03": "amour yeux coeur love adore",
  "moment-04": "amour bisou kiss love",
  "moment-05": "amour coeurs love fleche",
  "moment-06": "amour love craquer",
  "moment-07": "serrer amour tendresse hug",
  "moment-08": "film popcorn regarder serie",
  "moment-09": "choque surpris cache regarde",
  "moment-10": "boisson matin pause tasse",
  "moment-11": "drama potin popcorn courir",
  "moment-12": "popcorn suspicieuse doute fauteuil",
  "moment-13": "peur cache stress",
  "moment-14": "popcorn manger regarder",
  "moment-15": "boisson the brule",
  "moment-16": "drama potin popcorn courir",
  "moment-17": "cinema film popcorn tournage",
  "moment-18": "bof popcorn fauteuil blase",
  "moment-19": "argent billets riche sac money gagne",
  "moment-20": "argent billets riche business boss",
  "moment-21": "argent pluie riche money fric",
  "moment-22": "argent riche money dollars",
  "moment-23": "argent billets pluie money",
  "moment-24": "oups maladroit argent tomber",
  "moment-25": "pleurer triste larmes chagrin",
  "moment-26": "pleurer larmes triste couper",
  "moment-27": "pleurer larmes triste chagrin",
  "moment-28": "triste pleurer chagrin peine",
  "moment-29": "pluie nuage pleurer triste",
  "moment-30": "pleurer triste nuage courage",
  "moment-31": "sauvage feu clash",
  "moment-32": "clash explosion feu moquer",
  "moment-33": "flamme chaud top",
  "moment-34": "doigt feu clash",
  "moment-35": "micro rap chanter feu",
  "moment-36": "jongler feu boules",
  "moment-37": "tresor coffre argent riche or",
  "moment-38": "king trone couronne boss",
  "moment-39": "chef megaphone patron",
  "moment-40": "magicien baguette magique",
  "moment-41": "queen couronne princesse",
  "moment-42": "argent cartons danse",
};
