/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as ApiWippSplatRouteImport } from './routes/api/wipp/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWippSplatRoute = ApiWippSplatRouteImport.update({
  id: '/api/wipp/$',
  path: '/api/wipp/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy': typeof PrivacyRoute
  '/site': typeof SiteRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/g/$token': typeof GTokenRoute
  '/t/$code': typeof TCodeRoute
  '/api/wipp/$': typeof ApiWippSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy': typeof PrivacyRoute
  '/site': typeof SiteRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/g/$token': typeof GTokenRoute
  '/t/$code': typeof TCodeRoute
  '/api/wipp/$': typeof ApiWippSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/privacy': typeof PrivacyRoute
  '/site': typeof SiteRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/g/$token': typeof GTokenRoute
  '/t/$code': typeof TCodeRoute
  '/api/wipp/$': typeof ApiWippSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/delete-account'
    | '/privacy'
    | '/site'
    | '/support'
    | '/terms'
    | '/g/$token'
    | '/t/$code'
    | '/api/wipp/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/delete-account'
    | '/privacy'
    | '/site'
    | '/support'
    | '/terms'
    | '/g/$token'
    | '/t/$code'
    | '/api/wipp/$'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/delete-account'
    | '/privacy'
    | '/site'
    | '/support'
    | '/terms'
    | '/g/$token'
    | '/t/$code'
    | '/api/wipp/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  PrivacyRoute: typeof PrivacyRoute
  SiteRoute: typeof SiteRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  GTokenRoute: typeof GTokenRoute
  TCodeRoute: typeof TCodeRoute
  ApiWippSplatRoute: typeof ApiWippSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wipp/$': {
      id: '/api/wipp/$'
      path: '/api/wipp/$'
      fullPath: '/api/wipp/$'
      preLoaderRoute: typeof ApiWippSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  PrivacyRoute: PrivacyRoute,
  SiteRoute: SiteRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  GTokenRoute: GTokenRoute,
  TCodeRoute: TCodeRoute,
  ApiWippSplatRoute: ApiWippSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
